### ISSUE TITLE
Typo in exterior lighting

### ISSUE THREAD

**Issue by lymereJ** [pnnl/BEM-for-PRM#16]
https://github.com/pnnl/BEM-for-PRM/blob/2fc709ebb794e00d18efb8cea8851d94bbb71236/content/user_guide/add_compliance_data/user_data_exterior_lights.md?plain=1#L74

perimiter instead of perimeter

**Comment by weilixu** [comment]
Thanks for catching the typo! It has been updated. closing the issue.
